### ISSUE TITLE
Add tenant with access token

### ISSUE THREAD

**Issue by yannick-beot-sp** [yannick-beot-sp/vscode-sailpoint-identitynow#18]
Sometimes, it is easier to connect to a tenant with an existing access token.
At this moment, only PAT (Personal Access Token) is possible.
When adding a tenant, it should be possible to add a tenant with an access token.
Authentication method (PAT or AT) shall be stored along tenant info.

How to manage the access token expiration/refresh? By using authentication provider, VSCode has some account management, but it is not a well known feature and it might not help invalidate or refresh a tenant.

How to mark a tenant with an expired access token? We may need to update the icon based on the access token validity.

**Comment by volker-juergensen-sp** [comment]
Interesting idea. Since we can configure the Access Token lifetime in IDN, you can work for more than an hour. To make it practical, the setting for idle needs to be put also to several hours.
I have not seen (yet) an option to set the refresh token behavior - if that would be set to several days (and extendet when actively used) then the expiration would no longer be a problem. I still prefer short idle and access token lifetimes, but then have a longer refresh token.
In case an IDP is involved, the IDP will participate in managing the session.

**Comment by yannick-beot-sp** [comment]
Implemented in 0.0.12
