### ISSUE TITLE
"cannot get password" error on mac VSCODE

### ISSUE THREAD

**Issue by e-MANe** [yannick-beot-sp/vscode-sailpoint-identitynow#23]
I keep getting "cannot get password" error on the bottom right on VSCode on a mac after a day or so of usage, this has happened with multiple environments ? is this something other users are experiencing as well ? Thanks for all your hard work with this extension again. PS: I use PAT for Auth
<img width="1518" alt="Screen Shot 2022-08-16 at 11 09 16 AM" src="https://user-images.githubusercontent.com/111372113/184916986-9cacb295-daea-4957-898c-8643a6e58079.png">

**Comment by yannick-beot-sp** [comment]
Another user on Mac was also experiencing this issue.
After removing and adding the tenant again, it was OK. Can you try this for one of your tenant?

**Comment by joebogash** [comment]
I'm also running into this issue. it seems to occur after every reboot.

**Comment by rob-buskens-sp** [comment]
I had this error. I believe what I ended up doing to resolve it was remove the folder ~/Library/Application Support/Code (take a copy!) which was rebuilt on next start up. Have not had the issue since. I can't find the web site that led me to this...

Reinstalling vscode didn't work as that directory hung around.

**Comment by stephen-holinaty-sp** [comment]
I frequently have this occur, and have to remove/re-add all of my connected tenants.  its almost as though the password store gets corrupted.
