### ISSUE TITLE
Read Only Tenant Setting defaulted to ON. 

### ISSUE THREAD

**Issue by GeoffAtIDW** [yannick-beot-sp/vscode-sailpoint-identitynow#75]
**Is your feature request related to a problem? Please describe.**
When connecting to a Production tenant, I would like to be able to pull down the code to view it if there is an issue, or to compare to another environment, however I do not want to make ANY changes to this environment. 

Having no way to turn off the automatic updated is a risk for accidental configuration changes. 

**Describe the solution you'd like**
I would like a configuration option that would disable all writes to the tenant making it a Read-Only connection. I would also like this to be defaulted to ON, so that accidental changes are not made to the environment.

**Describe alternatives you've considered**
The only alternative is to NOT user the extension for these tenants. 

**Additional context**

**Comment by yannick-beot-sp** [comment]
New tenant will be read-only be default.
Existing tenants will be writable as this is the past behavior.
A lock at the tenant level will allow to mark the tenant as read-only or writable
![image](https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/assets/82362286/d8171ad2-d7b2-473e-bca5-271e252970b5)

**Comment by GeoffAtIDW** [comment]
This looks like it will function as desired. Looking forward to testing it out once released.

This is a good workaround for Issue #76 as well.

**Comment by yannick-beot-sp** [comment]
Edition is now disabled for read-only tenants.
But now, I need to ensure that any possible action are disabled as well.
So, I need to go through all possible action eventually...

**Comment by yannick-beot-sp** [comment]
@GeoffAtIDW What is the expected behavior for you if the tenant is read-only in case of a command?
Think when you are enabling or disabling a workflow, triggering the aggregation of a source, or importing configuration?
Do you want to:
1. Throw an error "Tenant is read-only"?
2. Ask for confirmation "Do you really want to do that since the tenant is read-only"?
3. Try to mask any command that would "write"?

**Comment by iobeidi** [comment]
Hey @GeoffAtIDW  and @yannick-beot-sp, I think it's an awesome idea to have the read-only; however, ISC already has some of the scope ready, ex: sp:sources:read.
Would it really be necessary to change the whole plugin for that, or is it something that you can control on the PAT/ISC level?

**Comment by GeoffAtIDW** [comment]
@yannick-beot-sp For the initial launch, I would go with whatever was easiest to implement. A warning or info message stating that the tenant is set to read-only would be in line with other software. I would think that masking all of the write commands might be a lot for now, although having them visible but greyed out and not clickable might be beneficial to show possible options. In a future state, you could possibly enable/allow certain commands in a hybrid state. 

The primary concern of my use case is with the automatic upload of changes to the tenant upon a save command, since it is the same save command in almost all applications. My use case is less concerned with commands that require you to go to a context menu and select the option, as that requires active thought to get to, and would not be accidentally done by a user who may think they are saving a file in another application. 

@iobeidi That is an interesting idea, however that would need to be configured on all objects being looked at by the plugin, and I am not sure if there is a read scope for each of the ones that the plugin uses currently (although I admittedly have not looked closely.) It would be something to consider.

**Comment by yannick-beot-sp** [comment]
@iobeidi You can restrict the scope on the PAT you are using either when you are creating the PAT or afterwards.
If the necessary scope in not present and needed for some operation in the plugin, you would get a 403 error.

**Comment by yannick-beot-sp** [comment]
@GeoffAtIDW Thanks Geoff for your feedback.
I think I made up my mind: I will go for a warning.

**Comment by volker-juergensen-sp** [comment]
Hi all,
I’d like to add a slightly different perspective, also making it easier for Yannick for a first thing…

It may be a simple approach to have a “global” switch read-only (default it on launch as a preference a user can set) that can be switched to write-allowed.
Value: Better acceptance for some environments as its harder to destroy something

A next step could be a setting per source. So a user can determine the sensitive sources and default them to “read only” while the playground is easy to reach
Value: Still easy to implement and better protection

Another approach: Hopefully the names of scopes follow some convention, so you can read from the access token the scopes and find some things like sources_readonly -> disable the edit for sources, show visually in the UI
Value: A mid-expert-user may not easily analyze a 403 error

Volker Jürgensen


Von: GeoffAtIDW ***@***.***>
Datum: Dienstag, 30. April 2024 um 15:04
An: yannick-beot-sp/vscode-sailpoint-identitynow ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [yannick-beot-sp/vscode-sailpoint-identitynow] Read Only Tenant Setting defaulted to ON. (Issue #75)
@yannick-beot-sp For the initial launch, I would go with whatever was easiest to implement. A warning or info message stating that the tenant is set to read-only would be in line with other software. I would think that masking all of the write


@yannick-beot-sp<https://urldefense.com/v3/__https:/github.com/yannick-beot-sp__;!!MsNKLpFGsw!OvmJ97IAJHx6ruy9cKw5wEs-vEdSTlRULLOKs11Of3-ZamRx6DMF-QlkyiNQbKnKqcGf76HP0oRKjhskHFeMVvgwPCK8f5IDGA$> For the initial launch, I would go with whatever was easiest to implement. A warning or info message stating that the tenant is set to read-only would be in line with other software. I would think that masking all of the write commands might be a lot for now, although having them visible but greyed out and not clickable might be beneficial to show possible options. In a future state, you could possibly enable/allow certain commands in a hybrid state.

The primary concern of my use case is with the automatic upload of changes to the tenant upon a save command, since it is the same save command in almost all applications. My use case is less concerned with commands that require you to go to a context menu and select the option, as that requires active thought to get to, and would not be accidentally done by a user who may think they are saving a file in another application.

@iobeidi<https://urldefense.com/v3/__https:/github.com/iobeidi__;!!MsNKLpFGsw!OvmJ97IAJHx6ruy9cKw5wEs-vEdSTlRULLOKs11Of3-ZamRx6DMF-QlkyiNQbKnKqcGf76HP0oRKjhskHFeMVvgwPCIbOlmXCQ$> That is an interesting idea, however that would need to be configured on all objects being looked at by the plugin, and I am not sure if there is a read scope for each of the ones that the plugin uses currently (although I admittedly have not looked closely.) It would be something to consider.

**Comment by yannick-beot-sp** [comment]
As part of v1.3.0
